export const acceptedNutrients = [
    "Water",
    "Energy",
    "Protein",
    "Total lipid (fat)",
    "Carbohydrate, by difference",
    "Fiber, total dietary",
    "Calcium, Ca",
    "Iron, Fe",
    "Magnesium, Mg",
    "Phosphorus, P",
    "Potassium, K",
    "Sodium, Na",
    "Zinc, Zn",
    "Copper, Cu",
    "Manganese, Mn",
    "Selenium, Se",
    "Fluoride, F",
    "Vitamin C, total ascorbic acid",
    "Thiamin",
    "Riboflavin",
    "Niacin",
    "Pantothenic acid",
    "Vitamin B-6",
    "Folate, total",
    "Vitamin B-12",
    "Vitamin A, IU",
    "Fatty acids, total saturated",
    "Fatty acids, total monounsaturated",
    "Fatty acids, total polyunsaturated",
    "Fatty acids, total trans",
    "20:5 n-3 (EPA)",
    "22:5 n-3 (DPA)",
    "22:6 n-3 (DHA)",
    "Cholesterol",
    "Choline, total",
    "Retinol",
    "Vitamin E (alpha-tocopherol)",
    "Vitamin D (D2 + D3), International Units",
    "Vitamin K (phylloquinone)"
]

export const nutrinentRequirements = [
    2000,
    8000,
    100,
    60,
    100,
    10,
    600,
    17,
    400,
    1200,
    3000,
    2000,
    20,
    2,
    2,
    100,
    50,
    100,
    2,
    3,
    20,
    7,
    3,
    200,
    3,
    3000,
    30,
    25,
    5,
    0,
    0.02,
    0.05,
    0.3,
    500,
    300,
    200,
    4,
    300,
    100
]