version: "3.7"

services: 
  api:
    volumes:
      - .:/app
    working_dir: /app
    container_name: api
    image: stringie/whf:node-puppeteer
    networks:
      - foodnet
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command: npm run start

  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - foodnet
    
networks:
  foodnet: